services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9052:9000"

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow_server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: >
      mlflow server 
      --backend-store-uri ./mlruns 
      --default-artifact-root ./mlruns 
      --host 0.0.0.0

volumes:
  portainer_data:
